### ISSUE TITLE
How can I control the max length of the platoon?

### ISSUE THREAD

**Issue by wrs777** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#1]
Very interested in your demo. Now I wanna change the size of platoon, so which part should I modify?

**Comment by sraddon** [comment]
Platoons are created automatically iin two ways:
1. When a vehicle first spawns, it determines whether the vehicle in front is in a platoon it wants to be in, if so it joins it else it creates a new platoon. (line 89 - 103 in simulationManager.py)
2. When a platoon comes to a complete stop, it will merge with the platoon in front if the are compatible (line 118-123 in simulation.py).

If you want to spawn in a whole platoon at once, you can increase the traffic scale within the relevent call to setUpSimulation (second argument) for the simulation you're running which will spawn the number of cars you set it to simultaneously whenever the scenario wants to add a new car. This will have the effect of instantly spawning a platoon. It will also increase the amount of traffic within the scenario however so you may need to adjust the corresponding rou.xml file for the map.

There is no limit on the number of vehicles that can be in a platoon currently within the code, if you wanted to add that functionality you would need to add extra conditionals in getReleventPlatoon in simulationManager.py and canMerge in platoon.py .

**Comment by wrs777** [comment]
Thx a lot. I'll have a try according to your advice.




------------------ 原始邮件 ------------------
发件人: "Sam Raddon"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 晚上6:24
收件人: "sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM"<SUMO-V2X-Communication-Research-Platooning-and-CIM@noreply.github.com>;
抄送: "。沉默╰’"<422395267@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM] Howcan I control the max length of the platoon? (#1)




Platoons are created automatically iin two ways:
  
When a vehicle first spawns, it determines whether the vehicle in front is in a platoon it wants to be in, if so it joins it else it creates a new platoon. (line 89 - 103 in simulationManager.py)
 
When a platoon comes to a complete stop, it will merge with the platoon in front if the are compatible (line 118-123 in simulation.py).
  
If you want to spawn in a whole platoon at once, you can increase the traffic scale within the relevent call to setUpSimulation (second argument) for the simulation you're running which will spawn the number of cars you set it to simultaneously whenever the scenario wants to add a new car. This will have the effect of instantly spawning a platoon. It will also increase the amount of traffic within the scenario however so you may need to adjust the corresponding rou.xml file for the map.
 
There is no limit on the number of vehicles that can be in a platoon currently within the code, if you wanted to add that functionality you would need to add extra conditionals in getReleventPlatoon in simulationManager.py and canMerge in platoon.py .

**Comment by wrs777** [comment]
now I've used setUpSimulation to set the number of cars when it is spawn. But it seems that I can only set the number as a static number. How can I make it randomly? For example, in the same intersection, sometimes the number is 2, but in the next step, it comes to 3.

**Comment by sraddon** [comment]
So in setupSimulation you can set the traffic scale, which sets the amount of vehicles that spawn in whenever sumo wants to spawn a vehicle. This has the (convenient) side-effect of creating a platoon. I am currently unaware of any way to change this mid-simulation using traci. You could of course randomise it at in the set up script but a single value would persist for the whole simulation. You can change it mid simulation in the gui (slider at the top) but I'm not sure how useful that will be to you. 

You may have to come up with your own solution to solve this problem. One way that I experimented with before I used traffic scale was to have traffic lights at the edges of each map, bursting the traffic in once a platoon has reached a specific length. You can control traffic lights and set random intervals using [this](https://sumo.dlr.de/wiki/TraCI/Change_Traffic_Lights_State). While I think this could do the trick, im not sure it will be the best solution, Good Luck!

An aside just in case I've misunderstood your question: In terms of getting the platoons to spawn in at random intervals, this can be done by changing the scenario files. At the moment they are configured to be generated at a constant rate however you can change the rou file to change this. See [here](https://sumo.dlr.de/wiki/Definition_of_Vehicles,_Vehicle_Types,_and_Routes) for the different options (see the title Repeated vehicles (Flows)).

**Comment by HappyDay-design** [comment]
> now I've used setUpSimulation to set the number of cars when it is spawn. But it seems that I can only set the number as a static number. How can I make it randomly? For example, in the same intersection, sometimes the number is 2, but in the next step, it comes to 3.

Hello. Did you find the solution to modify the platoon size?
