### ISSUE TITLE
How to create my own platoon vehicles by my simulation scene？

### ISSUE THREAD

**Issue by zhaotuo0815** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#11]
hello, developer, thank you for your help, I want to create my own platoon vehicles by my simulation scene, but I met some problem (like the picture), so how to create my own platoon vehicles by my simulation scene.
![getspeed_error](https://user-images.githubusercontent.com/59630993/197342976-34eb5105-438f-4af5-9084-93dc6cf6697a.png)

**Comment by sraddon** [comment]
Hi,
Sorry for the very late reply!
I think this may be the same issue as this (broken with new version): https://github.com/sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM/issues/10
Looking to spend some time fixing it soon but for now can use the older version. Let me know how you get on.
