### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by AlexanderInUM** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#12]
Dear :
Would you mind recommending some papers regarding your project?

Thanks~

**Comment by sraddon** [comment]
Hi,
As far as I'm aware I haven't heard of any papers being based on it apart from my own dissertation, I've previously uploaded my methodology to this answer if you're interested: https://github.com/sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM/issues/4

**Comment by AlexanderInUM** [comment]
Thanks!

**Comment by AlexanderInUM** [comment]
How may I cite this work/part of the paper?

**Comment by sraddon** [comment]
I believe I cited this for that term in my dissertation. This paper might be worth a read: Zohdy, I. H. & Rakha, H. A., 2016. Intersection Management via Vehicle Connectivity: The Intersection Cooperative Adaptive Cruise Control System Concept. Journal of Intelligent Transportation Systems, 20(1), pp. 17-32.

**Comment by sraddon** [comment]
I'm not sure the whole dissertation is publically available and what would constitute your ability to cite me within the guidelines of your university. I would ask your mentor and then let me know what details you need for a citation. Ill then do some docs on the project so it's easier for others.

**Comment by AlexanderInUM** [comment]
> I'm not sure the whole dissertation is publically available and what would constitute your ability to cite me within the guidelines of your university. I would ask your mentor and then let me know what details you need for a citation. Ill then do some docs on the project so it's easier for others.

I want to cite the whole process of your experiment.

**Comment by AlexanderInUM** [comment]
I want to cite the whole process of your experiment (using MLA or APA format). Then I will provide my understandings and revisions based on yours.

**Comment by AlexanderInUM** [comment]
> 

Do you have the MLA or APA format quotation to provide for this work?

**Comment by SunTianzhHERE** [comment]
hi do u have some format quotation for this work? how could you solve it ?

**Comment by SunTianzhHERE** [comment]
@AlexanderInUM
