### ISSUE TITLE
Can you provide your dissertation so that I can follow your platooning strategy. 

### ISSUE THREAD

**Issue by SJ-L** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#2]
As the the title says. Thank you very much!

**Comment by sraddon** [comment]
Hi, not sure I can provide the full dissertation here due to university guidelines, but here is the relevent chapter for the design of the experiments.
[Design of Experiments.pdf](https://github.com/sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM/files/5584573/Design.of.Experiments.pdf)

**Comment by SJ-L** [comment]
Received your file. Thank you very much.
