### ISSUE TITLE
Platooning in sumo

### ISSUE THREAD

**Issue by nabila-bermad** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#3]
Hello,
I think that you have a lot experience in platooning and sumo, and I will be very happy  if you can help me. so, I have created a scenario of a platoon compound of one truck leader and seven electric vehicles. In fact, I want to make some security simulations on this platoon. But, when I have used simpla and Traci
[Bejaia.zip](https://github.com/sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM/files/5886558/Bejaia.zip)

 to enforce the platoon and control the platoon leader, I think it does not work.
please find attached the created files to conduct my simulations.
Please let me know your feedback on the configuration I provided and
What have I done wrong.
Thanks in advance,
Nabila
Bejaia university.

**Comment by sraddon** [comment]
Hi Nabila,

Sorry for the late reply on this! I don't really have much experience using the simpla extension for SUMO/Traci unfortunately. I seem to remember looking at it when I first started off this project but for some reason decided not to use it and instead wrote my own bespoke code to achieve platooning. I'm probably as knowledgable about it as you are! 

The only thing I have spotted is that you are defining types for your platooning vehicles and placing it in your simpla config but then not assigning that type to any vehicles in your route config for the scenario; that could by why it isn't working? (this is in Bejaia.rou.xml).

Sorry I couldn't be of more help.

Thanks,
Sam

**Comment by nabila-bermad** [comment]
Hi Sam,
Thank you for your reply, in fact, I have fixed  my platoon using simpla,
but now I am looking for how to configure the communication between
vehicles to achieve some security simulation?
Do you have any idea?
Thanks,
Nabila

**Comment by sraddon** [comment]
Nice one! Unfortunately I'm not much help for the security part, I didn't implement anything like that for my project :( Good luck though!

**Comment by SJ-L** [comment]
Hi, may I know how do you fix the simpla problem? @nabila-bila
