### ISSUE TITLE
Request for the methodology part

### ISSUE THREAD

**Issue by lisong2019** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#4]
Hi, could you provide the methodology part of your dissertation/publiactions? 
That would be really helpful for understanding your settings.

**Comment by sraddon** [comment]
Hi,

I think I already provided this as an answer to another issue: https://github.com/sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM/issues/2

Take a look there and if you need anything more let me know :) Ill mark this issue as closed for now.

**Comment by lisong2019** [comment]
Hi Sraddon
Good to hear from you, I have noticed issue#2 and read that part before. However, this part did not introduce the methodology of how to form a platoon or zipping. It would be really helpful to ensure that I understand the right logic of the methods you proposed (i.g. the platoons are only allowed to merge when the former platoon is stopping)

**Comment by sraddon** [comment]
Hi, That is the only part of the dissertation regarding how the experiments were designed. The only other parts I have are the literature survey and the results (which I don't really want to publically publish). The dissertation was not written to dive very deeply into the code, it was more of a high level view of how it works. There is no specific code documentation apart from the small readme.
The methodology in terms of how the experiments were run can be found in the pdf in the other issue, it is section 4.6
