### ISSUE TITLE
Platoon in this Intersection

### ISSUE THREAD

**Issue by HappyDay-design** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#5]
Hi. Thank you for sharing this project.

I want to create more scenarios with platoon but I don't understand the code related to platoon adjustment.
Option 1: I want to fix the number of cars in a platoon of 5 cars, how do I adjust it?
Option 2: I want to let the length of the platoon be flexible but in the range of 2-6 cars. 
So is there any way to adjust it? Thank you

**Comment by sraddon** [comment]
Hi,
I had some spare time today so implemented this, If you pull from source you should find you can now set the max platoon size. If you look at the difference of the change hopefully that will give you some idea of how I did it. If you have any more feature requests please don't hesitate to get stuck in. I'm very happy to look at any changes you may want to make/go through a review process to get other people's contributions onto the main branch.
