### ISSUE TITLE
error that happened when using the scenario 3,4

### ISSUE THREAD

**Issue by Krisat88** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#6]
Hi Sam,
There is an error that happened when using the scenario 3,4
"Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error)."
How Can I solve the problem?
Thank you very much.

**Comment by HappyDay-design** [comment]
> Hi Sam, There is an error that happened when using the scenario 3,4 "Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown Quitting (on error)." How Can I solve the problem? Thank you very much.

Hello.

AttributeError: module 'traci' has no attribute 'trafficlights'
The module is now called trafficlight (without the "s"). You have to change 'trafficlights' to 'trafficlight' in coding

**Comment by Krisat88** [comment]
> > Hi Sam, There is an error that happened when using the scenario 3,4 "Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown Quitting (on error)." How Can I solve the problem? Thank you very much.
> 
> Hello.
> 
> AttributeError: module 'traci' has no attribute 'trafficlights' The module is now called trafficlight (without the "s"). You have to change 'trafficlights' to 'trafficlight' in coding

Thank you very much for helping!
The problem has solved

**Comment by sraddon** [comment]
I have pushed this fix to the master branch. Thanks for the above.
