### ISSUE TITLE
Distance between each vehicle in platoon

### ISSUE THREAD

**Issue by HappyDay-design** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#7]
Hello. Thank you for sharing your model 
I ran the model and I think the platoons here are not correct

![image](https://user-images.githubusercontent.com/82990411/149622286-72403dea-04cc-4ec5-9434-e62cd33431a3.png)

According to platoon theory when moving the vehicle flow will keep the same distance between the cars and this distance is quite small, about 15m because the cars share information with each other. 
But when I run the model and measure, this gap is quite large.

**Comment by sraddon** [comment]
Hi,
As it currently stands I want to keep the general platoon behaviour of the code the same as what it was when I conducted by dissertation work and don't really have the time to invest to improve the algorithm further. If you wanted to improve or change the algorithm, I can try to make the code easier to extend via allowing different classes for platoon management to be used per scenario or something like that. Perhaps if you wanted to fix the above or improve the algorithm we could review the code you have and have a conversation about how we can get it into master while still preserving the original platoon behaviour.
