### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Ballad-on** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#8]
It's my great honor to read your document, but I have the following problems in reproducing your project. How can I solve them?thanks
![TS9LWL94K2M RP7L~R)RWRQ](https://user-images.githubusercontent.com/67771008/159425407-31c3d1cd-3d71-4fd6-a337-3529a35aab58.png)

**Comment by sraddon** [comment]
Hi,
I haven't been able to reproduce this, it seems to be working fine for me. Could you confirm that you've got the latest version of the code and that the files are unedited locally?

`..\SUMO-V2X-Communication-Research-Platooning-and-CIM\src> python .\scenario_runner.py`
`Please enter map name, available maps are: Blackwell, Intersection, Roundabout: Intersection`
`Please enter scenario number, available numbers are: 1, 2, 3, 4, 5: 1`
