### ISSUE TITLE
Are there any relevant references

### ISSUE THREAD

**Issue by Daniel-DHu** [sraddon/SUMO-V2X-Communication-Research-Platooning-and-CIM#9]
Are there any relevant references. Thank u very much!

**Comment by sraddon** [comment]
Hi what do you mean by this, references to other work taken in the literature review?

**Comment by Daniel-DHu** [comment]
I would like to ask if you have sent similar articles that I can study and quote!

**Comment by sraddon** [comment]
Sorry not that I know of, would recommend going through your universities library for trying to find similar articles/projects.

**Comment by SunTianzhHERE** [comment]
hi do u have some format quotation for this work? how could you solve it ?
